#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "src/color.h"
#include "src/drawer.h"
#include "src/framebuffer.h"
#include "src/graphics/font.h"
#include "src/graphics/image.h"
#include "src/graphics/rasterfont.h"
#include "src/graphics/shape.h"
#include "src/printer.h"
#include "src/rasterizer.h"

void drawRainbow(FrameBuffer *fb, int x, int y) {
    Color red, orange, yellow, green, blue, purple;
    initColor(&red, "FF0000");
    initColor(&orange, "FF7700");
    initColor(&yellow, "FFFF00");
    initColor(&green, "009900");
    initColor(&blue, "000099");
    initColor(&purple, "990099");

    fillSquareArea(fb, x - 8, y + 4, x + 20, y + 6, red);
    fillSquareArea(fb, x - 8, y + 7, x + 20, y + 9, orange);
    fillSquareArea(fb, x - 8, y + 10, x + 20, y + 12, yellow);
    fillSquareArea(fb, x - 8, y + 13, x + 20, y + 15, green);
    fillSquareArea(fb, x - 8, y + 16, x + 20, y + 18, blue);
    fillSquareArea(fb, x - 8, y + 19, x + 20, y + 21, purple);
}

int main() {
    FrameBuffer fb = initFrameBuffer();

    //Initialization
    Color white, black, grey, pink, background;
    Color orange, yellow, green;

    initColor(&orange, "ff7800");
    initColor(&yellow, "FFFF00");
    initColor(&green, "00ff00");
    initColor(&white, "FFFFFF");
    initColor(&black, "000000");
    initColor(&grey, "77797A");
    initColor(&pink, "FF8AD1");
    initColor(&background, "0d1b46");

    Shape s;
    int offsetX = 800, offsetY = 500;

    char c;
    scanf("%c", &c);
    c = tolower(c);

    printf("\033[H\033[J");

    if (c == 'a') {
        initShape(&s, 2);
        initPolygon(&(s.polygons[0]), 7);
        s.polygons[0].vertices[0].x = offsetX + 60;
        s.polygons[0].vertices[0].y = offsetY + 110;
        s.polygons[0].vertices[1].x = offsetX + 80;
        s.polygons[0].vertices[1].y = offsetY + 110;
        s.polygons[0].vertices[2].x = offsetX + 40;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 0;
        s.polygons[0].vertices[3].y = offsetY + 110;
        s.polygons[0].vertices[4].x = offsetX + 20;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 27;
        s.polygons[0].vertices[5].y = offsetY + 90;
        s.polygons[0].vertices[6].x = offsetX + 53;
        s.polygons[0].vertices[6].y = offsetY + 90;

        initPolygon(&(s.polygons[1]), 3);
        s.polygons[1].vertices[0].x = offsetX + 28;
        s.polygons[1].vertices[0].y = offsetY + 75;
        s.polygons[1].vertices[1].x = offsetX + 52;
        s.polygons[1].vertices[1].y = offsetY + 75;
        s.polygons[1].vertices[2].x = offsetX + 40;
        s.polygons[1].vertices[2].y = offsetY + 34;
    } else if (c == 'b') {
        initShape(&s, 3);
        initPolygon(&(s.polygons[0]), 9);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 110;
        s.polygons[0].vertices[2].x = offsetX + 64;
        s.polygons[0].vertices[2].y = offsetY + 110;
        s.polygons[0].vertices[3].x = offsetX + 80;
        s.polygons[0].vertices[3].y = offsetY + 96;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 60;
        s.polygons[0].vertices[5].x = offsetX + 70;
        s.polygons[0].vertices[5].y = offsetY + 50;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 40;
        s.polygons[0].vertices[7].x = offsetX + 80;
        s.polygons[0].vertices[7].y = offsetY + 15;
        s.polygons[0].vertices[8].x = offsetX + 66;
        s.polygons[0].vertices[8].y = offsetY + 0;

        initPolygon(&(s.polygons[1]), 6);
        s.polygons[1].vertices[0].x = offsetX + 20;
        s.polygons[1].vertices[0].y = offsetY + 14;
        s.polygons[1].vertices[1].x = offsetX + 20;
        s.polygons[1].vertices[1].y = offsetY + 43;
        s.polygons[1].vertices[2].x = offsetX + 55;
        s.polygons[1].vertices[2].y = offsetY + 43;
        s.polygons[1].vertices[3].x = offsetX + 60;
        s.polygons[1].vertices[3].y = offsetY + 38;
        s.polygons[1].vertices[4].x = offsetX + 60;
        s.polygons[1].vertices[4].y = offsetY + 20;
        s.polygons[1].vertices[5].x = offsetX + 55;
        s.polygons[1].vertices[5].y = offsetY + 14;

        initPolygon(&(s.polygons[2]), 6);
        s.polygons[2].vertices[0].x = offsetX + 20;
        s.polygons[2].vertices[0].y = offsetY + 60;
        s.polygons[2].vertices[1].x = offsetX + 54;
        s.polygons[2].vertices[1].y = offsetY + 60;
        s.polygons[2].vertices[2].x = offsetX + 61;
        s.polygons[2].vertices[2].y = offsetY + 67;
        s.polygons[2].vertices[3].x = offsetX + 61;
        s.polygons[2].vertices[3].y = offsetY + 90;
        s.polygons[2].vertices[4].x = offsetX + 55;
        s.polygons[2].vertices[4].y = offsetY + 95;
        s.polygons[2].vertices[5].x = offsetX + 20;
        s.polygons[2].vertices[5].y = offsetY + 95;
    } else if (c == 'c') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 20);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 20;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 90;
        s.polygons[0].vertices[2].x = offsetX + 17;
        s.polygons[0].vertices[2].y = offsetY + 110;
        s.polygons[0].vertices[3].x = offsetX + 64;
        s.polygons[0].vertices[3].y = offsetY + 110;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 90;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 70;
        s.polygons[0].vertices[6].x = offsetX + 65;
        s.polygons[0].vertices[6].y = offsetY + 70;
        s.polygons[0].vertices[7].x = offsetX + 65;
        s.polygons[0].vertices[7].y = offsetY + 83;
        s.polygons[0].vertices[8].x = offsetX + 57;
        s.polygons[0].vertices[8].y = offsetY + 92;
        s.polygons[0].vertices[9].x = offsetX + 24;
        s.polygons[0].vertices[9].y = offsetY + 92;
        s.polygons[0].vertices[10].x = offsetX + 15;
        s.polygons[0].vertices[10].y = offsetY + 80;
        s.polygons[0].vertices[11].x = offsetX + 15;
        s.polygons[0].vertices[11].y = offsetY + 29;
        s.polygons[0].vertices[12].x = offsetX + 25;
        s.polygons[0].vertices[12].y = offsetY + 17;
        s.polygons[0].vertices[13].x = offsetX + 57;
        s.polygons[0].vertices[13].y = offsetY + 17;
        s.polygons[0].vertices[14].x = offsetX + 65;
        s.polygons[0].vertices[14].y = offsetY + 25;
        s.polygons[0].vertices[15].x = offsetX + 65;
        s.polygons[0].vertices[15].y = offsetY + 40;
        s.polygons[0].vertices[16].x = offsetX + 80;
        s.polygons[0].vertices[16].y = offsetY + 40;
        s.polygons[0].vertices[17].x = offsetX + 80;
        s.polygons[0].vertices[17].y = offsetY + 16;
        s.polygons[0].vertices[18].x = offsetX + 66;
        s.polygons[0].vertices[18].y = offsetY + 0;
        s.polygons[0].vertices[19].x = offsetX + 17;
        s.polygons[0].vertices[19].y = offsetY + 0;
    } else if (c == 'd') {
        initShape(&s, 2);
        initPolygon(&(s.polygons[0]), 6);
        s.polygons[0].vertices[0].x = offsetX + 80;
        s.polygons[0].vertices[0].y = offsetY + 16;
        s.polygons[0].vertices[1].x = offsetX + 66;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 0;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 0;
        s.polygons[0].vertices[3].y = offsetY + 110;
        s.polygons[0].vertices[4].x = offsetX + 64;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 90;

        initPolygon(&(s.polygons[1]), 6);
        s.polygons[1].vertices[0].x = offsetX + 65;
        s.polygons[1].vertices[0].y = offsetY + 27;
        s.polygons[1].vertices[1].x = offsetX + 56;
        s.polygons[1].vertices[1].y = offsetY + 16;
        s.polygons[1].vertices[2].x = offsetX + 15;
        s.polygons[1].vertices[2].y = offsetY + 16;
        s.polygons[1].vertices[3].x = offsetX + 15;
        s.polygons[1].vertices[3].y = offsetY + 93;
        s.polygons[1].vertices[4].x = offsetX + 55;
        s.polygons[1].vertices[4].y = offsetY + 94;
        s.polygons[1].vertices[5].x = offsetX + 65;
        s.polygons[1].vertices[5].y = offsetY + 80;
    } else if (c == 'e') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 110;
        s.polygons[0].vertices[2].x = offsetX + 80;
        s.polygons[0].vertices[2].y = offsetY + 110;
        s.polygons[0].vertices[3].x = offsetX + 80;
        s.polygons[0].vertices[3].y = offsetY + 94;
        s.polygons[0].vertices[4].x = offsetX + 16;
        s.polygons[0].vertices[4].y = offsetY + 94;
        s.polygons[0].vertices[5].x = offsetX + 16;
        s.polygons[0].vertices[5].y = offsetY + 62;
        s.polygons[0].vertices[6].x = offsetX + 50;
        s.polygons[0].vertices[6].y = offsetY + 62;
        s.polygons[0].vertices[7].x = offsetX + 50;
        s.polygons[0].vertices[7].y = offsetY + 48;
        s.polygons[0].vertices[8].x = offsetX + 16;
        s.polygons[0].vertices[8].y = offsetY + 48;
        s.polygons[0].vertices[9].x = offsetX + 16;
        s.polygons[0].vertices[9].y = offsetY + 18;
        s.polygons[0].vertices[10].x = offsetX + 80;
        s.polygons[0].vertices[10].y = offsetY + 18;
        s.polygons[0].vertices[11].x = offsetX + 80;
        s.polygons[0].vertices[11].y = offsetY + 0;
    } else if (c == 'f') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 10);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 110;
        s.polygons[0].vertices[2].x = offsetX + 16;
        s.polygons[0].vertices[2].y = offsetY + 110;
        s.polygons[0].vertices[3].x = offsetX + 16;
        s.polygons[0].vertices[3].y = offsetY + 62;
        s.polygons[0].vertices[4].x = offsetX + 50;
        s.polygons[0].vertices[4].y = offsetY + 62;
        s.polygons[0].vertices[5].x = offsetX + 50;
        s.polygons[0].vertices[5].y = offsetY + 48;
        s.polygons[0].vertices[6].x = offsetX + 16;
        s.polygons[0].vertices[6].y = offsetY + 48;
        s.polygons[0].vertices[7].x = offsetX + 16;
        s.polygons[0].vertices[7].y = offsetY + 18;
        s.polygons[0].vertices[8].x = offsetX + 80;
        s.polygons[0].vertices[8].y = offsetY + 18;
        s.polygons[0].vertices[9].x = offsetX + 80;
        s.polygons[0].vertices[9].y = offsetY + 0;
    } else if (c == 'g') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 22);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 20;
        s.polygons[0].vertices[1].x = offsetX + 20;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 60;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 80;
        s.polygons[0].vertices[3].y = offsetY + 20;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 34;
        s.polygons[0].vertices[5].x = offsetX + 66;
        s.polygons[0].vertices[5].y = offsetY + 34;
        s.polygons[0].vertices[6].x = offsetX + 66;
        s.polygons[0].vertices[6].y = offsetY + 27;
        s.polygons[0].vertices[7].x = offsetX + 53;
        s.polygons[0].vertices[7].y = offsetY + 14;
        s.polygons[0].vertices[8].x = offsetX + 27;
        s.polygons[0].vertices[8].y = offsetY + 14;
        s.polygons[0].vertices[9].x = offsetX + 14;
        s.polygons[0].vertices[9].y = offsetY + 27;
        s.polygons[0].vertices[10].x = offsetX + 14;
        s.polygons[0].vertices[10].y = offsetY + 85;
        s.polygons[0].vertices[11].x = offsetX + 24;
        s.polygons[0].vertices[11].y = offsetY + 96;
        s.polygons[0].vertices[12].x = offsetX + 56;
        s.polygons[0].vertices[12].y = offsetY + 96;
        s.polygons[0].vertices[13].x = offsetX + 66;
        s.polygons[0].vertices[13].y = offsetY + 84;
        s.polygons[0].vertices[14].x = offsetX + 66;
        s.polygons[0].vertices[14].y = offsetY + 70;
        s.polygons[0].vertices[15].x = offsetX + 56;
        s.polygons[0].vertices[15].y = offsetY + 70;
        s.polygons[0].vertices[16].x = offsetX + 56;
        s.polygons[0].vertices[16].y = offsetY + 56;
        s.polygons[0].vertices[17].x = offsetX + 80;
        s.polygons[0].vertices[17].y = offsetY + 56;
        s.polygons[0].vertices[18].x = offsetX + 80;
        s.polygons[0].vertices[18].y = offsetY + 90;
        s.polygons[0].vertices[19].x = offsetX + 63;
        s.polygons[0].vertices[19].y = offsetY + 110;
        s.polygons[0].vertices[20].x = offsetX + 18;
        s.polygons[0].vertices[20].y = offsetY + 110;
        s.polygons[0].vertices[21].x = offsetX + 0;
        s.polygons[0].vertices[21].y = offsetY + 90;
    } else if (c == 'h') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 15;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 15;
        s.polygons[0].vertices[2].y = offsetY + 48;
        s.polygons[0].vertices[3].x = offsetX + 66;
        s.polygons[0].vertices[3].y = offsetY + 48;
        s.polygons[0].vertices[4].x = offsetX + 66;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 0;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 66;
        s.polygons[0].vertices[7].y = offsetY + 110;
        s.polygons[0].vertices[8].x = offsetX + 66;
        s.polygons[0].vertices[8].y = offsetY + 62;
        s.polygons[0].vertices[9].x = offsetX + 15;
        s.polygons[0].vertices[9].y = offsetY + 62;
        s.polygons[0].vertices[10].x = offsetX + 15;
        s.polygons[0].vertices[10].y = offsetY + 110;
        s.polygons[0].vertices[11].x = offsetX + 0;
        s.polygons[0].vertices[11].y = offsetY + 110;
    } else if (c == 'i') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 10;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 10;
        s.polygons[0].vertices[1].y = offsetY + 14;
        s.polygons[0].vertices[2].x = offsetX + 33;
        s.polygons[0].vertices[2].y = offsetY + 14;
        s.polygons[0].vertices[3].x = offsetX + 33;
        s.polygons[0].vertices[3].y = offsetY + 96;
        s.polygons[0].vertices[4].x = offsetX + 10;
        s.polygons[0].vertices[4].y = offsetY + 96;
        s.polygons[0].vertices[5].x = offsetX + 10;
        s.polygons[0].vertices[5].y = offsetY + 110;
        s.polygons[0].vertices[6].x = offsetX + 70;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 70;
        s.polygons[0].vertices[7].y = offsetY + 96;
        s.polygons[0].vertices[8].x = offsetX + 48;
        s.polygons[0].vertices[8].y = offsetY + 96;
        s.polygons[0].vertices[9].x = offsetX + 48;
        s.polygons[0].vertices[9].y = offsetY + 14;
        s.polygons[0].vertices[10].x = offsetX + 70;
        s.polygons[0].vertices[10].y = offsetY + 14;
        s.polygons[0].vertices[11].x = offsetX + 70;
        s.polygons[0].vertices[11].y = offsetY + 0;
    } else if (c == 'j') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 65;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 65;
        s.polygons[0].vertices[1].y = offsetY + 88;
        s.polygons[0].vertices[2].x = offsetX + 57;
        s.polygons[0].vertices[2].y = offsetY + 96;
        s.polygons[0].vertices[3].x = offsetX + 22;
        s.polygons[0].vertices[3].y = offsetY + 96;
        s.polygons[0].vertices[4].x = offsetX + 15;
        s.polygons[0].vertices[4].y = offsetY + 87;
        s.polygons[0].vertices[5].x = offsetX + 15;
        s.polygons[0].vertices[5].y = offsetY + 79;
        s.polygons[0].vertices[6].x = offsetX + 1;
        s.polygons[0].vertices[6].y = offsetY + 79;
        s.polygons[0].vertices[7].x = offsetX + 1;
        s.polygons[0].vertices[7].y = offsetY + 94;
        s.polygons[0].vertices[8].x = offsetX + 14;
        s.polygons[0].vertices[8].y = offsetY + 110;
        s.polygons[0].vertices[9].x = offsetX + 65;
        s.polygons[0].vertices[9].y = offsetY + 110;
        s.polygons[0].vertices[10].x = offsetX + 80;
        s.polygons[0].vertices[10].y = offsetY + 96;
        s.polygons[0].vertices[11].x = offsetX + 80;
        s.polygons[0].vertices[11].y = offsetY + 0;
    } else if (c == 'k') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 80;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 63;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 15;
        s.polygons[0].vertices[2].y = offsetY + 44;
        s.polygons[0].vertices[3].x = offsetX + 15;
        s.polygons[0].vertices[3].y = offsetY + 0;
        s.polygons[0].vertices[4].x = offsetX + 0;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 0;
        s.polygons[0].vertices[5].y = offsetY + 110;
        s.polygons[0].vertices[6].x = offsetX + 15;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 15;
        s.polygons[0].vertices[7].y = offsetY + 64;
        s.polygons[0].vertices[8].x = offsetX + 26;
        s.polygons[0].vertices[8].y = offsetY + 53;
        s.polygons[0].vertices[9].x = offsetX + 61;
        s.polygons[0].vertices[9].y = offsetY + 110;
        s.polygons[0].vertices[10].x = offsetX + 77;
        s.polygons[0].vertices[10].y = offsetY + 110;
        s.polygons[0].vertices[11].x = offsetX + 36;
        s.polygons[0].vertices[11].y = offsetY + 43;
    } else if (c == 'l') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 6);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 16;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 16;
        s.polygons[0].vertices[2].y = offsetY + 95;
        s.polygons[0].vertices[3].x = offsetX + 80;
        s.polygons[0].vertices[3].y = offsetY + 95;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 0;
        s.polygons[0].vertices[5].y = offsetY + 110;
    } else if (c == 'm') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 110;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 15;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 40;
        s.polygons[0].vertices[3].y = offsetY + 47;
        s.polygons[0].vertices[4].x = offsetX + 66;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 0;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 66;
        s.polygons[0].vertices[7].y = offsetY + 110;
        s.polygons[0].vertices[8].x = offsetX + 66;
        s.polygons[0].vertices[8].y = offsetY + 31;
        s.polygons[0].vertices[9].x = offsetX + 40;
        s.polygons[0].vertices[9].y = offsetY + 75;
        s.polygons[0].vertices[10].x = offsetX + 15;
        s.polygons[0].vertices[10].y = offsetY + 31;
        s.polygons[0].vertices[11].x = offsetX + 15;
        s.polygons[0].vertices[11].y = offsetY + 110;
    } else if (c == 'n') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 10);
        s.polygons[0].vertices[0].x = offsetX + 65;
        s.polygons[0].vertices[0].y = offsetY + 80;
        s.polygons[0].vertices[1].x = offsetX + 15;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 0;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 0;
        s.polygons[0].vertices[3].y = offsetY + 110;
        s.polygons[0].vertices[4].x = offsetX + 15;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 15;
        s.polygons[0].vertices[5].y = offsetY + 33;
        s.polygons[0].vertices[6].x = offsetX + 65;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 80;
        s.polygons[0].vertices[7].y = offsetY + 110;
        s.polygons[0].vertices[8].x = offsetX + 80;
        s.polygons[0].vertices[8].y = offsetY + 0;
        s.polygons[0].vertices[9].x = offsetX + 65;
        s.polygons[0].vertices[9].y = offsetY + 0;
    } else if (c == 'o') {
        initShape(&s, 2);
        initPolygon(&(s.polygons[0]), 8);
        s.polygons[0].vertices[0].x = offsetX + 20;
        s.polygons[0].vertices[0].y = offsetY + 110;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 90;
        s.polygons[0].vertices[2].x = offsetX + 0;
        s.polygons[0].vertices[2].y = offsetY + 20;
        s.polygons[0].vertices[3].x = offsetX + 20;
        s.polygons[0].vertices[3].y = offsetY + 0;
        s.polygons[0].vertices[4].x = offsetX + 60;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 20;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 90;
        s.polygons[0].vertices[7].x = offsetX + 60;
        s.polygons[0].vertices[7].y = offsetY + 110;

        initPolygon(&(s.polygons[1]), 8);
        s.polygons[0].vertices[0].x = offsetX + 26;
        s.polygons[0].vertices[0].y = offsetY + 94;
        s.polygons[0].vertices[1].x = offsetX + 12;
        s.polygons[0].vertices[1].y = offsetY + 80;
        s.polygons[0].vertices[2].x = offsetX + 12;
        s.polygons[0].vertices[2].y = offsetY + 30;
        s.polygons[0].vertices[3].x = offsetX + 26;
        s.polygons[0].vertices[3].y = offsetY + 16;
        s.polygons[0].vertices[4].x = offsetX + 54;
        s.polygons[0].vertices[4].y = offsetY + 16;
        s.polygons[0].vertices[5].x = offsetX + 68;
        s.polygons[0].vertices[5].y = offsetY + 30;
        s.polygons[0].vertices[6].x = offsetX + 68;
        s.polygons[0].vertices[6].y = offsetY + 80;
        s.polygons[0].vertices[7].x = offsetX + 54;
        s.polygons[0].vertices[7].y = offsetY + 94;
    } else if (c == 'p') {
        initShape(&s, 2);
        initPolygon(&(s.polygons[0]), 8);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 68;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 80;
        s.polygons[0].vertices[2].y = offsetY + 10;
        s.polygons[0].vertices[3].x = offsetX + 80;
        s.polygons[0].vertices[3].y = offsetY + 51;
        s.polygons[0].vertices[4].x = offsetX + 68;
        s.polygons[0].vertices[4].y = offsetY + 60;
        s.polygons[0].vertices[5].x = offsetX + 15;
        s.polygons[0].vertices[5].y = offsetY + 60;
        s.polygons[0].vertices[6].x = offsetX + 15;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 0;
        s.polygons[0].vertices[7].y = offsetY + 110;

        initPolygon(&(s.polygons[1]), 6);
        s.polygons[1].vertices[0].x = offsetX + 15;
        s.polygons[1].vertices[0].y = offsetY + 47;
        s.polygons[1].vertices[1].x = offsetX + 15;
        s.polygons[1].vertices[1].y = offsetY + 13;
        s.polygons[1].vertices[2].x = offsetX + 57;
        s.polygons[1].vertices[2].y = offsetY + 13;
        s.polygons[1].vertices[3].x = offsetX + 67;
        s.polygons[1].vertices[3].y = offsetY + 23;
        s.polygons[1].vertices[4].x = offsetX + 67;
        s.polygons[1].vertices[4].y = offsetY + 38;
        s.polygons[1].vertices[5].x = offsetX + 57;
        s.polygons[1].vertices[5].y = offsetY + 47;
    } else if (c == 'q') {
        initShape(&s, 2);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 20;
        s.polygons[0].vertices[1].x = offsetX + 20;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 60;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 80;
        s.polygons[0].vertices[3].y = offsetY + 20;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 90;
        s.polygons[0].vertices[5].x = offsetX + 75;
        s.polygons[0].vertices[5].y = offsetY + 95;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 100;
        s.polygons[0].vertices[7].x = offsetX + 71;
        s.polygons[0].vertices[7].y = offsetY + 110;
        s.polygons[0].vertices[8].x = offsetX + 65;
        s.polygons[0].vertices[8].y = offsetY + 105;
        s.polygons[0].vertices[9].x = offsetX + 60;
        s.polygons[0].vertices[9].y = offsetY + 110;
        s.polygons[0].vertices[10].x = offsetX + 20;
        s.polygons[0].vertices[10].y = offsetY + 110;
        s.polygons[0].vertices[11].x = offsetX + 0;
        s.polygons[0].vertices[11].y = offsetY + 90;

        initPolygon(&(s.polygons[1]), 11);
        s.polygons[1].vertices[0].x = offsetX + 17;
        s.polygons[1].vertices[0].y = offsetY + 25;
        s.polygons[1].vertices[1].x = offsetX + 23;
        s.polygons[1].vertices[1].y = offsetY + 19;
        s.polygons[1].vertices[2].x = offsetX + 57;
        s.polygons[1].vertices[2].y = offsetY + 19;
        s.polygons[1].vertices[3].x = offsetX + 63;
        s.polygons[1].vertices[3].y = offsetY + 25;
        s.polygons[1].vertices[4].x = offsetX + 63;
        s.polygons[1].vertices[4].y = offsetY + 80;
        s.polygons[1].vertices[5].x = offsetX + 63;
        s.polygons[1].vertices[5].y = offsetY + 85;
        s.polygons[1].vertices[6].x = offsetX + 51;
        s.polygons[1].vertices[6].y = offsetY + 73;
        s.polygons[1].vertices[7].x = offsetX + 42;
        s.polygons[1].vertices[7].y = offsetY + 82;
        s.polygons[1].vertices[8].x = offsetX + 51;
        s.polygons[1].vertices[8].y = offsetY + 91;
        s.polygons[1].vertices[9].x = offsetX + 23;
        s.polygons[1].vertices[9].y = offsetY + 91;
        s.polygons[1].vertices[10].x = offsetX + 17;
        s.polygons[1].vertices[10].y = offsetY + 85;
    } else if (c == 'r') {
        initShape(&s, 2);
        initPolygon(&(s.polygons[0]), 11);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 110;
        s.polygons[0].vertices[2].x = offsetX + 15;
        s.polygons[0].vertices[2].y = offsetY + 110;
        s.polygons[0].vertices[3].x = offsetX + 15;
        s.polygons[0].vertices[3].y = offsetY + 56;
        s.polygons[0].vertices[4].x = offsetX + 63;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 110;
        s.polygons[0].vertices[6].x = offsetX + 35;
        s.polygons[0].vertices[6].y = offsetY + 56;
        s.polygons[0].vertices[7].x = offsetX + 65;
        s.polygons[0].vertices[7].y = offsetY + 56;
        s.polygons[0].vertices[8].x = offsetX + 80;
        s.polygons[0].vertices[8].y = offsetY + 46;
        s.polygons[0].vertices[9].x = offsetX + 80;
        s.polygons[0].vertices[9].y = offsetY + 14;
        s.polygons[0].vertices[10].x = offsetX + 65;
        s.polygons[0].vertices[10].y = offsetY + 0;

        initPolygon(&(s.polygons[1]), 6);
        s.polygons[1].vertices[0].x = offsetX + 14;
        s.polygons[1].vertices[0].y = offsetY + 40;
        s.polygons[1].vertices[1].x = offsetX + 14;
        s.polygons[1].vertices[1].y = offsetY + 14;
        s.polygons[1].vertices[2].x = offsetX + 58;
        s.polygons[1].vertices[2].y = offsetY + 14;
        s.polygons[1].vertices[3].x = offsetX + 66;
        s.polygons[1].vertices[3].y = offsetY + 21;
        s.polygons[1].vertices[4].x = offsetX + 66;
        s.polygons[1].vertices[4].y = offsetY + 35;
        s.polygons[1].vertices[5].x = offsetX + 58;
        s.polygons[1].vertices[5].y = offsetY + 40;
    } else if (c == 's') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 28);
        s.polygons[0].vertices[0].x = offsetX + 80;
        s.polygons[0].vertices[0].y = offsetY + 35;
        s.polygons[0].vertices[1].x = offsetX + 66;
        s.polygons[0].vertices[1].y = offsetY + 35;
        s.polygons[0].vertices[2].x = offsetX + 66;
        s.polygons[0].vertices[2].y = offsetY + 23;
        s.polygons[0].vertices[3].x = offsetX + 58;
        s.polygons[0].vertices[3].y = offsetY + 15;
        s.polygons[0].vertices[4].x = offsetX + 22;
        s.polygons[0].vertices[4].y = offsetY + 15;
        s.polygons[0].vertices[5].x = offsetX + 14;
        s.polygons[0].vertices[5].y = offsetY + 24;
        s.polygons[0].vertices[6].x = offsetX + 14;
        s.polygons[0].vertices[6].y = offsetY + 39;
        s.polygons[0].vertices[7].x = offsetX + 22;
        s.polygons[0].vertices[7].y = offsetY + 49;
        s.polygons[0].vertices[8].x = offsetX + 66;
        s.polygons[0].vertices[8].y = offsetY + 49;
        s.polygons[0].vertices[9].x = offsetX + 80;
        s.polygons[0].vertices[9].y = offsetY + 61;
        s.polygons[0].vertices[10].x = offsetX + 80;
        s.polygons[0].vertices[10].y = offsetY + 96;
        s.polygons[0].vertices[11].x = offsetX + 66;
        s.polygons[0].vertices[11].y = offsetY + 110;
        s.polygons[0].vertices[12].x = offsetX + 14;
        s.polygons[0].vertices[12].y = offsetY + 110;
        s.polygons[0].vertices[13].x = offsetX + 0;
        s.polygons[0].vertices[13].y = offsetY + 95;
        s.polygons[0].vertices[14].x = offsetX + 0;
        s.polygons[0].vertices[14].y = offsetY + 85;
        s.polygons[0].vertices[15].x = offsetX + 14;
        s.polygons[0].vertices[15].y = offsetY + 85;
        s.polygons[0].vertices[16].x = offsetX + 14;
        s.polygons[0].vertices[16].y = offsetY + 90;
        s.polygons[0].vertices[17].x = offsetX + 20;
        s.polygons[0].vertices[17].y = offsetY + 96;
        s.polygons[0].vertices[18].x = offsetX + 60;
        s.polygons[0].vertices[18].y = offsetY + 96;
        s.polygons[0].vertices[19].x = offsetX + 68;
        s.polygons[0].vertices[19].y = offsetY + 89;
        s.polygons[0].vertices[20].x = offsetX + 68;
        s.polygons[0].vertices[20].y = offsetY + 73;
        s.polygons[0].vertices[21].x = offsetX + 60;
        s.polygons[0].vertices[21].y = offsetY + 65;
        s.polygons[0].vertices[22].x = offsetX + 14;
        s.polygons[0].vertices[22].y = offsetY + 65;
        s.polygons[0].vertices[23].x = offsetX + 0;
        s.polygons[0].vertices[23].y = offsetY + 47;
        s.polygons[0].vertices[24].x = offsetX + 0;
        s.polygons[0].vertices[24].y = offsetY + 14;
        s.polygons[0].vertices[25].x = offsetX + 14;
        s.polygons[0].vertices[25].y = offsetY + 0;
        s.polygons[0].vertices[26].x = offsetX + 65;
        s.polygons[0].vertices[26].y = offsetY + 0;
        s.polygons[0].vertices[27].x = offsetX + 80;
        s.polygons[0].vertices[27].y = offsetY + 17;
    } else if (c == 't') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 8);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 16;
        s.polygons[0].vertices[2].x = offsetX + 32;
        s.polygons[0].vertices[2].y = offsetY + 16;
        s.polygons[0].vertices[3].x = offsetX + 32;
        s.polygons[0].vertices[3].y = offsetY + 110;
        s.polygons[0].vertices[4].x = offsetX + 48;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 48;
        s.polygons[0].vertices[5].y = offsetY + 16;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 16;
        s.polygons[0].vertices[7].x = offsetX + 80;
        s.polygons[0].vertices[7].y = offsetY + 0;
    } else if (c == 'u') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 16;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 16;
        s.polygons[0].vertices[2].y = offsetY + 84;
        s.polygons[0].vertices[3].x = offsetX + 24;
        s.polygons[0].vertices[3].y = offsetY + 94;
        s.polygons[0].vertices[4].x = offsetX + 56;
        s.polygons[0].vertices[4].y = offsetY + 94;
        s.polygons[0].vertices[5].x = offsetX + 64;
        s.polygons[0].vertices[5].y = offsetY + 84;
        s.polygons[0].vertices[6].x = offsetX + 64;
        s.polygons[0].vertices[6].y = offsetY + 0;
        s.polygons[0].vertices[7].x = offsetX + 80;
        s.polygons[0].vertices[7].y = offsetY + 0;
        s.polygons[0].vertices[8].x = offsetX + 80;
        s.polygons[0].vertices[8].y = offsetY + 96;
        s.polygons[0].vertices[9].x = offsetX + 68;
        s.polygons[0].vertices[9].y = offsetY + 110;
        s.polygons[0].vertices[10].x = offsetX + 12;
        s.polygons[0].vertices[10].y = offsetY + 110;
        s.polygons[0].vertices[11].x = offsetX + 0;
        s.polygons[0].vertices[11].y = offsetY + 96;
    } else if (c == 'v') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 6);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 14;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 40;
        s.polygons[0].vertices[2].y = offsetY + 72;
        s.polygons[0].vertices[3].x = offsetX + 66;
        s.polygons[0].vertices[3].y = offsetY + 0;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 40;
        s.polygons[0].vertices[5].y = offsetY + 110;
    } else if (c == 'w') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 13);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 14;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 25;
        s.polygons[0].vertices[2].y = offsetY + 78;
        s.polygons[0].vertices[3].x = offsetX + 35;
        s.polygons[0].vertices[3].y = offsetY + 0;
        s.polygons[0].vertices[4].x = offsetX + 45;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 53;
        s.polygons[0].vertices[5].y = offsetY + 78;
        s.polygons[0].vertices[6].x = offsetX + 66;
        s.polygons[0].vertices[6].y = offsetY + 0;
        s.polygons[0].vertices[7].x = offsetX + 80;
        s.polygons[0].vertices[7].y = offsetY + 0;
        s.polygons[0].vertices[8].x = offsetX + 65;
        s.polygons[0].vertices[8].y = offsetY + 110;
        s.polygons[0].vertices[9].x = offsetX + 46;
        s.polygons[0].vertices[9].y = offsetY + 110;
        s.polygons[0].vertices[10].x = offsetX + 40;
        s.polygons[0].vertices[10].y = offsetY + 78;
        s.polygons[0].vertices[11].x = offsetX + 34;
        s.polygons[0].vertices[11].y = offsetY + 110;
        s.polygons[0].vertices[12].x = offsetX + 15;
        s.polygons[0].vertices[12].y = offsetY + 110;
    } else if (c == 'x') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 12);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 15;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 40;
        s.polygons[0].vertices[2].y = offsetY + 40;
        s.polygons[0].vertices[3].x = offsetX + 64;
        s.polygons[0].vertices[3].y = offsetY + 0;
        s.polygons[0].vertices[4].x = offsetX + 80;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 48;
        s.polygons[0].vertices[5].y = offsetY + 56;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 110;
        s.polygons[0].vertices[7].x = offsetX + 64;
        s.polygons[0].vertices[7].y = offsetY + 110;
        s.polygons[0].vertices[8].x = offsetX + 40;
        s.polygons[0].vertices[8].y = offsetY + 70;
        s.polygons[0].vertices[9].x = offsetX + 15;
        s.polygons[0].vertices[9].y = offsetY + 110;
        s.polygons[0].vertices[10].x = offsetX + 0;
        s.polygons[0].vertices[10].y = offsetY + 110;
        s.polygons[0].vertices[11].x = offsetX + 32;
        s.polygons[0].vertices[11].y = offsetY + 56;
    } else if (c == 'y') {
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 9);
        s.polygons[0].vertices[0].x = offsetX + 47;
        s.polygons[0].vertices[0].y = offsetY + 56;
        s.polygons[0].vertices[1].x = offsetX + 80;
        s.polygons[0].vertices[1].y = offsetY + 0;
        s.polygons[0].vertices[2].x = offsetX + 64;
        s.polygons[0].vertices[2].y = offsetY + 0;
        s.polygons[0].vertices[3].x = offsetX + 40;
        s.polygons[0].vertices[3].y = offsetY + 40;
        s.polygons[0].vertices[4].x = offsetX + 15;
        s.polygons[0].vertices[4].y = offsetY + 0;
        s.polygons[0].vertices[5].x = offsetX + 0;
        s.polygons[0].vertices[5].y = offsetY + 0;
        s.polygons[0].vertices[6].x = offsetX + 33;
        s.polygons[0].vertices[6].y = offsetY + 56;
        s.polygons[0].vertices[7].x = offsetX + 33;
        s.polygons[0].vertices[7].y = offsetY + 110;
        s.polygons[0].vertices[8].x = offsetX + 47;
        s.polygons[0].vertices[8].y = offsetY + 110;
    } else { // c == z
        initShape(&s, 1);
        initPolygon(&(s.polygons[0]), 10);
        s.polygons[0].vertices[0].x = offsetX + 0;
        s.polygons[0].vertices[0].y = offsetY + 0;
        s.polygons[0].vertices[1].x = offsetX + 0;
        s.polygons[0].vertices[1].y = offsetY + 14;
        s.polygons[0].vertices[2].x = offsetX + 63;
        s.polygons[0].vertices[2].y = offsetY + 14;
        s.polygons[0].vertices[3].x = offsetX + 0;
        s.polygons[0].vertices[3].y = offsetY + 96;
        s.polygons[0].vertices[4].x = offsetX + 0;
        s.polygons[0].vertices[4].y = offsetY + 110;
        s.polygons[0].vertices[5].x = offsetX + 80;
        s.polygons[0].vertices[5].y = offsetY + 110;
        s.polygons[0].vertices[6].x = offsetX + 80;
        s.polygons[0].vertices[6].y = offsetY + 96;
        s.polygons[0].vertices[7].x = offsetX + 20;
        s.polygons[0].vertices[7].y = offsetY + 96;
        s.polygons[0].vertices[8].x = offsetX + 80;
        s.polygons[0].vertices[8].y = offsetY + 15;
        s.polygons[0].vertices[9].x = offsetX + 80;
        s.polygons[0].vertices[9].y = offsetY + 0;
    }

    scanlineFill(&fb, &s, pink);

    sleep(1);

    return 0;
}
